### PR TITLE
Added ava testing for slugify utility

### PR DESCRIPTION
**Pull request by hyperhtml**
- [x] Added ava to dev dependencies
- [x] Created tests to cover the slugify utility

PR for Issue: https://github.com/0xadada/vital-cause/issues/4

### CODE REVIEW

**Comment by hyperhtml** [comment]
Just updated my branch to contain lint changes in master branch.

**Comment by 0xadada** [comment]
@hyperhtml could you rebase of master again, i just pushed a change.

**Comment by hyperhtml** [comment]
Awesome @0xadada Its rebased now.   Thank you!

**Comment by 0xadada** [comment]
@hyperhtml looks like `yarn eslint` is failing because `test.js` isn't using singlequotes. fix that and i'll merge

**Comment by 0xadada** [comment]
lol j/k, i'll merge and just fix it.

resolves https://github.com/0xadada/vital-cause/issues/4

**Pull request merged**
